services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  api:
    build: ./api
    environment:
      API_PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: api_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
